#!/bin/bash

OUTPUT=$(uglifyjs droposaurus.js -m -r '$,require,exports')
echo ";$OUTPUT" > droposaurus.min.js

OUTPUT=$(uglifyjs simple-dropdown.js -m -r '$,require,exports')
echo ";$OUTPUT" > simple-dropdown.min.js